/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Site": {
      "type": "sst.aws.Nuxt"
      "url": string
    }
    "TwitchClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitchClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Users": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}